Repository TripComeTrue/TripComeTrue_BE, pull requests merged in 2024-01, with the labels that each got.

#5 [fix] service단에서 return 값 변경
  src/main/java/com/haejwo/tripcometrue/domain/member/controller/MemberController.java
  src/main/java/com/haejwo/tripcometrue/domain/member/service/MemberService.java
Labels: fix

#21 [fix] 자동 배포 에러 수정 및 테스트
  .github/workflows/deploy.yml
Labels: fix

#23 [fix] CD 빌드 테스트 코드 수정
  .github/workflows/deploy.yml
Labels: fix

#25 #6 여행지 관련 기본기능 구현
  build.gradle
  src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceController.java
  src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/domain/place/dto/PlaceDto.java
  src/main/java/com/haejwo/tripcometrue/domain/place/dto/request/PlaceFilterRequestDTO.java
  src/main/java/com/haejwo/tripcometrue/domain/place/dto/request/PlaceRequestDTO.java
  src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceResponseDTO.java
  src/main/java/com/haejwo/tripcometrue/domain/place/entity/Place.java
  src/main/java/com/haejwo/tripcometrue/domain/place/exception/PlaceNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceCustomRepositoryImpl.java
  src/main/java/com/haejwo/tripcometrue/domain/place/repositroy/PlaceRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
  src/main/java/com/haejwo/tripcometrue/global/config/AppConfig.java
  src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
  src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
Labels: enhancement, feat

#44 [hotfix] cd 스크립트 수정
  Dockerfile
Labels: fix

#47 [fix] 자동 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: fix

#48 [hotfix] docker compose 파일 설정 수정
  docker-compose.yml
Labels: fix

#40 [feat] S3 이미지 업로드 및 삭제 기능 구현
  build.gradle
  src/main/java/com/haejwo/tripcometrue/global/config/S3Config.java
  src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
  src/main/java/com/haejwo/tripcometrue/global/exception/GlobalExceptionRestAdvice.java
  src/main/java/com/haejwo/tripcometrue/global/s3/controller/S3Controller.java
  src/main/java/com/haejwo/tripcometrue/global/s3/controller/S3ControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/global/s3/exception/FileEmptyException.java
  src/main/java/com/haejwo/tripcometrue/global/s3/exception/FileMaxSizeExceededException.java
  src/main/java/com/haejwo/tripcometrue/global/s3/exception/FileNotExistsException.java
  src/main/java/com/haejwo/tripcometrue/global/s3/exception/FileUploadFailException.java
  src/main/java/com/haejwo/tripcometrue/global/s3/response/S3UploadResponseDto.java
  src/main/java/com/haejwo/tripcometrue/global/s3/service/S3Service.java
  src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/http/s3/imagedelete.http
  src/test/http/s3/imageupload.http
  src/test/resources/application.yml
Labels: enhancement, feat

#49 [feat] 여행후기 관련 엔티티 & 예외 구현
  src/main/java/com/haejwo/tripcometrue/domain/member/controller/MemberControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/domain/member/exception/UserInvalidAccessException.java
  src/main/java/com/haejwo/tripcometrue/domain/place/exception/PlaceNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordController.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/request/TripRecordRequestDto.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/TripRecordResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordImage.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordSchedule.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordScheduleImage.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordScheduleVideo.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordStore.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordTag.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordViewCount.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecordViewHistory.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/type/ExpenseRangeType.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/type/ExternalLinkTagType.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/type/HashTagType.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/type/TripRecordImageType.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/exception/ExpenseRangeTypeNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/exception/TripRecordNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordService.java
  src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
Labels: enhancement, feat

#60 [feat] 여행지 리뷰(PlaceReview) 관련 엔티티, 서비스, 리포지토리 1차 구현
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewController.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/request/RegisterPlaceReviewRequestDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/RegisterPlaceReviewResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/entity/PlaceReview.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/repository/PlaceReviewRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/service/PlaceReviewService.java
  src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
Labels: enhancement, feat

#73 [feat] 여행지 리뷰(PlaceReview) CRUD 기능 구현 (리스트 조회 제외)
  src/main/java/com/haejwo/tripcometrue/domain/likes/service/LikesService.java
  src/main/java/com/haejwo/tripcometrue/domain/member/entity/Member.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewController.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/request/DeletePlaceReviewRequestDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/request/PlaceReviewRequestDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/DeleteAllSuccessPlaceReviewResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/DeletePlaceReviewResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/DeleteSomeFailurePlaceReviewResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/dto/response/PlaceReviewResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/entity/PlaceReview.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/entity/PointType.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/exception/PlaceReviewAlreadyExistsException.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/exception/PlaceReviewDeleteAllFailureException.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/exception/PlaceReviewNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/repository/PlaceReviewRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/service/PlaceReviewService.java
  src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
  src/main/java/com/haejwo/tripcometrue/global/springsecurity/SpringSecurityConfig.java
  src/main/java/com/haejwo/tripcometrue/global/util/ResponseDTO.java
  src/test/http/review/place_review/place_review.http
Labels: enhancement, feat

#75 [feat] 여행지 세부페이지 지도기능 구현
  src/main/java/com/haejwo/tripcometrue/domain/place/controller/PlaceController.java
  src/main/java/com/haejwo/tripcometrue/domain/place/dto/response/PlaceMapInfoResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/place/service/PlaceService.java
  src/test/http/place/place_get.http
Labels: feat

#77 [feat] 여행후기와 여행지 엔티티 수정
  src/main/java/com/haejwo/tripcometrue/domain/place/entity/Place.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
Labels: feat

#110 [feat] 여행 후기 댓글, 대댓글(TripRecordComment) CRDU 기능 구현
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/controller/TripRecordCommentController.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/controller/TripRecordCommentControllerAdvice.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/dto/request/CommentRequestDto.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/dto/response/TripRecordCommentListResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/dto/response/TripRecordCommentResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/entity/TripRecordComment.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/exception/TripRecordCommentNotFoundException.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/repository/TripRecordCommentRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/service/TripRecordCommentService.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/controller/PlaceReviewController.java
  src/main/java/com/haejwo/tripcometrue/domain/review/placereview/service/PlaceReviewService.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/entity/TripRecord.java
  src/main/java/com/haejwo/tripcometrue/global/exception/ErrorCode.java
  src/test/http/comment/trip_record_comment.http
Labels: enhancement, feat

#120 [refactor] 도시 상세 환율 정보 조회 API 변경 및 로직 리팩토링 수정
  src/main/java/com/haejwo/tripcometrue/domain/city/controller/CityInfoReadController.java
  src/main/java/com/haejwo/tripcometrue/domain/city/service/CityInfoReadService.java
Labels: fix, refactor

#128 [fix] 로그인하지 않은 사용자도 여행 후기 댓글(TripRecordComment) 목록 조회 가능하도록 수정
  src/main/java/com/haejwo/tripcometrue/domain/comment/triprecord/service/TripRecordCommentService.java
Labels: fix

#130 [feat] 여행지 갤러리 Page 정보 추가
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/controller/TripRecordScheduleController.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule/TripRecordScheduleCustomRepository.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord_schedule/TripRecordScheduleCustomRepositoryImpl.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/service/TripRecordScheduleService.java
Labels: fix, feat

#134 [fix] store Response Dto 필드값 정리
  src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/CityStoreResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/PlaceStoreResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/store/dto/response/TripRecordStoreResponseDto.java
Labels: fix

#136 [feat] 여행후기 쇼츠 리스트 API 응답 데이터 추가
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/member/TripRecordVideoMemberResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/dto/response/triprecord_schedule_media/TripRecordHotShortsListResponseDto.java
  src/main/java/com/haejwo/tripcometrue/domain/triprecord/repository/triprecord/TripRecordRepositoryImpl.java
Labels: fix, feat

#139 [fix] 최신 여행 후기 totalCount 조회에서 여행 후기id에 따라 개수 변화 기능 수정
  src/main/java/com/haejwo/tripcometrue/domain/review/triprecordreview/repository/TripRecordReviewRepository.java
Labels: fix
